apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: udaanjee-ingress
  namespace: udaanjee
spec:
  rules:
    - host: api.udaanjee.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
